name: Lint Assets

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'resources/**/*.js'
      - 'resources/**/*.css'
      - 'biome.json'
      - 'eslint.config.js'
      - '.oxlintrc.json'
      - 'package-lock.json'
      - '.github/workflows/lint-assets.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        linter: ['biome', 'eslint', 'oxlint']
        include:
          - linter: 'biome'
            params: 'ci --reporter=github'

    name: Run ${{ matrix.linter }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up NPM
        uses: actions/setup-node@v6
      - run: npm ci
      - name: Lint code
        run: npx ${{ matrix.linter }} ${{ matrix.params  || '' }}